import { defineSignal } from "./signal-definition.js";

export const UI_SIGNAL_DEFINITIONS = Object.freeze([
  defineSignal({
    id: "ui_surface",
    polarity: "positive",
    weight: 8,
    reason: "UI, frontend, or browser surface wording",
    routing: true,
    source: "generic",
    patterns: [
      /\b(?:UI|UX|frontend|front-end|browser|viewport)\b/i,
      /前端|界面|页面|浏览器|视口|移动端布局|用户路径点击/,
    ],
  }),
  defineSignal({
    id: "ui_implementation",
    polarity: "positive",
    weight: 12,
    reason: "explicit implementation work on a user interface or frontend surface",
    routing: true,
    source: "generic",
    patterns: [
      /^(?![\s\S]*\bno\s+(?:frontend|front-end|UI|UX)\s+(?:changes?|implementation|work)\b)(?![\s\S]*(?:不|未|勿|别|无需)(?:实现|开发|修改|修复|落地|编码|接线|改造).{0,16}(?:前端|UI|UX|界面|页面))[\s\S]*(?:\b(?:UI|UX|frontend|front-end)\b|前端(?:页面|组件)?|界面|页面|(?:页面|界面)(?:交互|布局|样式)).{0,60}(?:实现|开发|修改|修复|落地|编码|接线|改造|\b(?:implement|build|code|fix|update|modify|wire|refactor)\b)/i,
      /^(?![\s\S]*\bno\s+(?:frontend|front-end|UI|UX)\s+(?:changes?|implementation|work)\b)(?![\s\S]*(?:不|未|勿|别|无需)(?:实现|开发|修改|修复|落地|编码|接线|改造).{0,16}(?:前端|UI|UX|界面|页面))[\s\S]*(?:实现|开发|修改|修复|落地|编码|接线|改造|\b(?:implement|build|code|fix|update|modify|wire|refactor)\b).{0,60}(?:\b(?:UI|UX|frontend|front-end)\b|前端(?:页面|组件)?|界面|页面|(?:页面|界面)(?:交互|布局|样式))/i,
    ],
  }),
  defineSignal({
    id: "ui_design_only",
    polarity: "negative",
    weight: -32,
    reason: "UI work is explicitly limited to design judgment without implementation",
    routing: false,
    negativeTargets: ["ui_implementation", "information_design", "ui_delivery_work"],
    suppressTargets: true,
    source: "generic",
    patterns: [
      /(?:只|仅|仅仅).{0,10}(?:评审|判断|讨论|评价).{0,30}(?:UI|UX|页面|界面|设计稿|信息架构|信息层级|状态字段|视觉|交互)/i,
      /(?:只|仅|仅仅).{0,10}(?:UI|UX|页面|界面|设计稿|信息架构|信息层级|状态字段|视觉|交互).{0,30}(?:评审|判断|讨论|评价)/i,
      /(?:只|仅|仅仅).{0,24}(?:设计(?:评审|判断|方案)?|评审.{0,12}(?:UI|UX|设计)|原型|线框图?|设计稿|布局评审).{0,50}(?:不(?:改|修改)代码|不实现|不开发|不落地)/i,
      /(?:不(?:改|修改)代码|不实现|不开发|不落地).{0,50}(?:只|仅|仅仅).{0,24}(?:设计(?:评审|判断|方案)?|评审.{0,12}(?:UI|UX|设计)|原型|线框图?|设计稿|布局评审)/i,
      /(?:\bdesign[-\s]?only\b|\bonly\b.{0,24}\b(?:review|evaluate|judge)\b.{0,24}\b(?:UI|UX|design|mockup|wireframe)\b).{0,60}\b(?:do\s+not|don't|without|no)\s+(?:implement|code|change|modify|build)/i,
      /\b(?:do\s+not|don't|without|no)\s+(?:implement|code|change|modify|build).{0,60}(?:\bdesign[-\s]?only\b|\bonly\b.{0,24}\b(?:review|evaluate|judge)\b.{0,24}\b(?:UI|UX|design|mockup|wireframe)\b)/i,
    ],
  }),
  defineSignal({
    id: "ui_cosmetic_only",
    polarity: "negative",
    weight: -24,
    reason: "UI work is explicitly limited to cosmetic presentation changes",
    routing: false,
    source: "generic",
    patterns: [
      /(?:只|仅|仅仅).{0,12}(?:调整|修改|改|优化).{0,50}(?:颜色|间距|字体|字号|图标|样式|布局|文案|视觉)/i,
      /(?:颜色|间距|字体|字号|图标|样式|布局|文案|视觉).{0,40}(?:只|仅|仅仅).{0,12}(?:调整|修改|改|优化)/i,
      /\bonly\b.{0,20}\b(?:adjust|change|modify|tweak|polish)\b.{0,50}\b(?:colou?r|spacing|typography|font|icons?|styles?|layout|copy|visuals?)\b/i,
      /\b(?:colou?r|spacing|typography|font|icons?|styles?|layout|copy|visuals?)\b.{0,40}\bonly\b.{0,20}\b(?:adjust|change|modify|tweak|polish)\b/i,
    ],
  }),
  defineSignal({
    id: "ui_delivery_work",
    polarity: "positive",
    weight: 13,
    reason: "implemented user-facing UI is being delivered through real data and a real user path",
    routing: true,
    source: "generic",
    patterns: [
      /(?:\b(?:UI|UX|frontend|front-end)\b|前端|界面|页面).{0,100}(?:实现完成|已经实现|接入?真实\s*(?:API|数据)|真实\s*(?:API|数据)|浏览器(?:验收|验证)|用户路径|端到端|\bE2E\b|\bimplemented\b|real\s+(?:API|data)|browser\s+(?:validation|acceptance|E2E)|user\s+path|ship(?:ped|ping)?|deliver(?:y|ed)?)/i,
      /(?:实现完成|已经实现|接入?真实\s*(?:API|数据)|真实\s*(?:API|数据)|浏览器(?:验收|验证)|用户路径|端到端|\bE2E\b|\bimplemented\b|real\s+(?:API|data)|browser\s+(?:validation|acceptance|E2E)|user\s+path|ship(?:ped|ping)?|deliver(?:y|ed)?).{0,100}(?:\b(?:UI|UX|frontend|front-end)\b|前端|界面|页面)/i,
      /(?:\b(?:UI|frontend|front-end)\b|前端|界面|页面).{0,50}(?:检查|排查|验证|check|inspect).{0,50}(?:console).{0,30}(?:network).{0,24}(?:error|错误|异常)/i,
      /(?:dashboard|控制台|仪表盘).{0,50}(?:实时数据|live\s+data).{0,60}(?:真实浏览器|real\s+browser).{0,60}(?:loading).{0,20}(?:empty).{0,20}(?:error)/i,
      /(?:runtime\s+events?|运行时事件).{0,50}(?:接到|接入|wire|wired).{0,30}(?:\bUI\b|前端|界面|页面).{0,60}(?:检查|验证|验|check|verify).{0,50}(?:network).{0,24}(?:console).{0,40}(?:移动端交互|mobile\s+interaction)/i,
      /(?:wire|接入|接到).{0,30}(?:runtime\s+events?|运行时事件).{0,30}(?:\bUI\b|前端|界面|页面).{0,60}(?:检查|验证|验|check|verify).{0,50}(?:network).{0,24}(?:console).{0,40}(?:移动端交互|mobile\s+interactions?)/i,
      /(?:implement|build|实现).{0,30}(?:dashboard|控制台|仪表盘).{0,40}(?:live\s+data|实时数据).{0,60}(?:validate|verify|验证).{0,40}(?:loading).{0,20}(?:failure|error|失败).{0,20}(?:permission|权限).{0,60}(?:real\s+browser\s+flow|真实浏览器(?:流程|路径)?)/i,
    ],
  }),
  defineSignal({
    id: "ui_surface_noise",
    polarity: "negative",
    weight: -30,
    reason: "UI or browser wording is explicitly described as noise",
    routing: false,
    negativeTargets: ["ui_surface"],
    suppressTargets: true,
    source: "generic",
    patterns: [
      /\b(?:UI|UX|frontend|front-end|browser|viewport)\b.{0,32}(?:noise|噪声)/i,
      /(?:noise|噪声).{0,32}\b(?:UI|UX|frontend|front-end|browser|viewport)\b/i,
      /(?:前端|界面|页面|浏览器|视口).{0,32}噪声|噪声.{0,32}(?:前端|界面|页面|浏览器|视口)/,
    ],
  }),
  defineSignal({
    id: "ui_example_discussion",
    polarity: "negative",
    weight: -30,
    reason: "UI or browser wording is discussed as documentation or an example, not used as a real UI task",
    routing: false,
    negativeTargets: ["ui_surface"],
    suppressTargets: true,
    source: "generic",
    patterns: [
      /(?:文档|README|readme|docs?|案例|示例|例子|examples?|展示|说明).{0,80}\b(?:UI|UX|frontend|front-end|browser|viewport)\b/i,
      /\b(?:UI|UX|frontend|front-end|browser|viewport)\b.{0,80}(?:文档|README|readme|docs?|案例|示例|例子|examples?|展示|说明)/i,
      /(?:文档|README|readme|docs?|案例|示例|例子|展示|说明).{0,80}(?:前端|界面|页面|浏览器|视口)/,
      /(?:前端|界面|页面|浏览器|视口).{0,80}(?:文档|README|readme|docs?|案例|示例|例子|展示|说明)/,
      /(?:不运行|不用运行|不执行|只解释|只是解释|只说明).{0,40}(?:UI|浏览器|页面|前端|browser)/i,
    ],
  }),
]);
