import {
  matchSemanticSignalComposition,
  semanticSignalReplacesDirectPatterns,
} from "./semantic-signals.js";
import {
  defineSignal as signal,
  type RuleSignal,
  type SignalDefinition,
  type SignalSource,
  type SignalValidationResult,
} from "./signal-definition.js";
import { UI_SIGNAL_DEFINITIONS } from "./signal-definitions-ui.js";

export type {
  RuleSignal,
  SignalDefinition,
  SignalPolarity,
  SignalSource,
  SignalValidationResult,
} from "./signal-definition.js";

export const SIGNAL_REGISTRY: readonly Readonly<SignalDefinition>[] = Object.freeze([
  signal({
    id: "goal_execute",
    polarity: "positive",
    weight: 18,
    reason: "explicit agent goal execution wording",
    routing: true,
    source: "pack",
    pack: "agent-goal",
    patterns: [
      /\/goal\b/i,
      /\b(?:create|start|use)\s+(?:a\s+)?goal\b/i,
      /\bgoal\s+(?:and\s+)?(?:start|execute|run|finish|verify)\b/i,
      /(?:创建|启动|使用).{0,8}(?:目标|goal)(?:.{0,30}(?:开始|开干|执行|跑|完成|闭环|验证|验收))?/i,
      /(?:目标|goal|长任务).{0,30}(?:开始|开干|执行|跑|完成|闭环|验证|验收)/i,
    ],
  }),
  signal({
    id: "goal_example_discussion",
    polarity: "negative",
    weight: -34,
    reason: "goal wording is discussed as documentation or an example, not used as an execution trigger",
    routing: false,
    negativeTargets: ["goal_execute"],
    suppressTargets: true,
    source: "pack",
    pack: "agent-goal",
    patterns: [
      /(?:文档|README|readme|docs?|documentation|guide|tutorial|案例|示例|例子|examples?|展示|说明).{0,80}(?:\/goal\b|创建目标|使用\s*goal|\bcreate\s+(?:a\s+)?goal\b|\buse\s+goal\b)/i,
      /(?:\/goal\b|创建目标|使用\s*goal|\bcreate\s+(?:a\s+)?goal\b|\buse\s+goal\b).{0,80}(?:文档|README|readme|docs?|documentation|guide|tutorial|案例|示例|例子|examples?|展示|说明|给用户看)/i,
      /(?:比如|例如|当我说).{0,40}(?:\/goal\b|创建目标|使用\s*goal)/i,
      /\b(?:discuss|explain)\b.{0,80}(?:\/goal\b|\bcreate\s+(?:a\s+)?goal\b|\buse\s+goal\b)/i,
      /(?:\/goal\b|\bcreate\s+(?:a\s+)?goal\b|\buse\s+goal\b).{0,80}\b(?:means?|explained|explaining|discussion|without\s+executing)\b/i,
    ],
  }),
  signal({
    id: "explicit_execute",
    polarity: "positive",
    weight: 8,
    reason: "explicit execution wording",
    routing: false,
    source: "generic",
    patterns: [
      /\b(?:implement|build|create|fix|repair|update|change|add|remove|refactor|run|execute|deploy|install|write|handle|investigate|resolve|diagnose|modify|edit)\b/i,
      /开干|开始处理|做完|实现|落地|修复|执行|开发|新增|修改|重构|处理|追查|调查|解决|排查/,
    ],
  }),
  signal({
    id: "real_validation",
    polarity: "positive",
    weight: 6,
    reason: "real-path validation wording",
    routing: false,
    source: "generic",
    patterns: [/真实入口|真实路径|浏览器验证|自己验证|逐项验证|e2e|smoke|验收/i],
  }),
  ...UI_SIGNAL_DEFINITIONS,
  signal({
    id: "ome_review_surface",
    polarity: "positive",
    weight: 10,
    reason: "OME AI-first draft approval workflow wording",
    routing: true,
    source: "pack",
    pack: "ome",
    patterns: [
      /\bOME\b.*(?:draft approval|experience)/i,
      /oh-my-experience.*(?:draft approval|experience)/i,
      /AI[-\s]?first.*(?:draft approval|review)/i,
      /experience draft approval|manual card creation|avoid user burden/i,
      /经验草稿审批|经验卡.*(?:审核|审批|review)|复盘.*(?:审核|审批)/,
    ],
  }),
  signal({
    id: "provider_adapter_boundary",
    polarity: "positive",
    weight: 12,
    reason: "provider adapter or shared hook runtime boundary wording",
    routing: true,
    source: "generic",
    patterns: [
      /(?:Claude\s+UserPromptSubmit|Codex\s+hook|provider[-\s]?neutral|additionalContext|fork\s+retrieval|retrieval\s+scoring)/i,
      /(?:不同\s*Agent|多入口适配|适配层|provider).{0,60}(?:召回|hook|runtime|运行时|分叉|同一套)/i,
      /(?:不要|不能|绝不能).{0,40}(?:分叉|fork).{0,40}(?:召回|retrieval|scoring)/i,
    ],
  }),
  signal({
    id: "dispatch_runtime_development",
    polarity: "positive",
    weight: 14,
    reason: "ai-dispatch runtime or provider subsystem development",
    routing: true,
    source: "pack",
    pack: "ai-dispatch",
    queryTerms: [
      "ai-dispatch-runtime-dev",
      "provider-adapter",
      "model-registry",
      "route-acceptance",
      "fallback-truth",
      "stream-runtime",
    ],
    patterns: [
      // Semantic composition is authoritative for routing; keep only a narrow
      // registry anchor for metadata/debug output.
      /\b(?:add|build|implement|develop|modify|change|fix|debug|refactor|migrate|integrate|wire|upgrade)\b.{0,24}\bai[-\s]?dispatch\b\s*(?:'s|[:：])?\s*(?:(?:the|a|an|new)\s+)?(?:provider\s*adapter|(?:model|provider)\s*registry|model\s*aliases?|model\s*resolver|route\s*resolver|(?:routing|route)\s*table|fallback\s*(?:chain|routing)|resume\s*runtime|stream(?:ing)?\s*runtime)\b/i,
    ],
  }),
  signal({
    id: "package_install_validation",
    polarity: "positive",
    weight: 12,
    reason: "package, tarball, or clean install validation wording",
    routing: true,
    source: "generic",
    patterns: [
      /\bnpm\s+pack\b|\btarball\s+install\b|\bpackage\s+install\s+smoke\b|\bnpx\s+smoke\b/i,
      /(?:临时目录|临时项目|clean\s+temp).{0,40}(?:安装|install)|(?:安装|install).{0,40}(?:tarball|npm\s+包|安装包)/i,
      /(?:发布|release|pack).{0,40}(?:验收|验证|smoke|安装包)/i,
    ],
  }),
  signal({
    id: "delivery_gate",
    polarity: "positive",
    weight: 12,
    reason: "delivery, final review, pre-submit, or acceptance gate wording",
    routing: true,
    source: "generic",
    patterns: [
      /(?:交付|收尾|提交前|pre[-\s]?submit|final\s+review|delivery).{0,50}(?:验收|review|检查|gate|自检|验证)/i,
      /(?:验收|自检).{0,30}(?:交付门禁|交付就绪|发布就绪|final\s+review|delivery\s+gate)/i,
      /(?:代码|改动|diff|分支|commit|PR|pull\s+request|release|版本|发布包).{0,50}(?:可以|能不能|能否|是否|是不是|准备好).{0,20}(?:提交|合并|交付|发布|开\s*PR)/i,
      /(?:可以|能不能|能否|是否|是不是|准备好).{0,20}(?:提交|合并|交付|发布|开\s*PR).{0,50}(?:代码|改动|diff|分支|commit|PR|pull\s+request|release|版本|发布包)/i,
      /(?:能不能|能否|是否|是不是).{0,16}(?:上线|交付)/i,
      /(?:发布|release).{0,20}(?:READY|NOT\s+READY)|(?:READY|NOT\s+READY).{0,20}(?:发布|release)/i,
      /(?:代码|diff|改动).{0,50}(?:最后|最终|最新).{0,30}(?:变更|修改|change).{0,50}(?:重新|再).{0,20}(?:交付验收|交付验证|delivery\s+(?:acceptance|validation))/i,
      /(?:修复|fix).{0,24}(?:完成|做完|done).{0,24}(?:不等于|does\s+not\s+mean|doesn't\s+mean|!=).{0,36}(?:发布就绪|可以发布|能发布|release[-\s]?ready|ready\s+to\s+release).{0,70}(?:单独|分别|separately).{0,24}(?:判断|评估|assess|judge).{0,40}(?:release\s+gate|发布\s*gate|发布门禁).{0,50}(?:真实用户路径|真实用户链路|用户路径|real\s+user\s+path)/i,
      /(?:代码|改动|diff|PR).{0,36}(?:能|可以).{0,12}(?:合并|merge).{0,60}(?:blocker|阻塞).{0,40}(?:可信)?(?:证据|evidence)/i,
      /\b(?:can|could|should|ready\s+to)\b.{0,24}\b(?:commit(?:ted)?|merge(?:d)?|ship(?:ped)?|release(?:d)?)\b/i,
      /\bP[012]\b.{0,40}\b(?:READY|NOT\s+READY|blockers?)\b/i,
      /\b(?:READY|NOT\s+READY)\b.{0,40}(?:\bP[012]\b|提交|合并|交付|发布|\bblockers?\b)/i,
      /(?:还有|是否有|有没有).{0,16}(?:blocker|阻塞项|阻断项)|\b(?:any|remaining)\s+blockers?\b/i,
    ],
  }),
  signal({
    id: "single_truth_version",
    polarity: "positive",
    weight: 12,
    reason: "single current truth, version, or compatibility-path convergence wording",
    routing: true,
    source: "generic",
    patterns: [
      /(?:只保留|收敛到|保持|统一到).{0,24}(?:单一|唯一|一个|当前)?(?:事实版本|真源|事实源|source\s+of\s+truth)/i,
      /(?:单一|唯一).{0,16}(?:事实版本|真源|事实源|source\s+of\s+truth)/i,
      /(?:双读双写|两套真相|多套版本|旧字段兼容|兼容旧逻辑|历史包袱).{0,32}(?:删除|清理|移除|不保留|收敛|不要)/i,
      /(?:删除|清理|移除|不保留|不要).{0,32}(?:双读双写|两套真相|多套版本|旧字段兼容|兼容旧逻辑|历史包袱)/i,
      /(?:current|当前).{0,50}(?:legacy|旧版|旧版本|旧读(?:取)?器?|旧写(?:入)?器?).{0,90}(?:收敛|统一|删除|移除|清理|converge|unify|remove|drop)/i,
      /(?:legacy|旧版|旧版本|旧读(?:取)?器?|旧写(?:入)?器?).{0,50}(?:current|当前).{0,90}(?:收敛|统一|删除|移除|清理|converge|unify|remove|drop)/i,
      /(?:收敛|统一|删除|移除|清理|converge|unify|remove|drop).{0,90}(?:current|当前).{0,50}(?:legacy|旧版|旧版本|旧读(?:取)?器?|旧写(?:入)?器?)/i,
      /(?:双读|双写|双读双写|dual\s+(?:readers?|writers?|read[-\s]?write)).{0,70}(?:收敛|统一|删除|移除|清理|converge|unify|remove|drop)/i,
      /(?:收敛|统一|删除|移除|清理|converge|unify|remove|drop).{0,40}(?:legacy|旧版|旧版本).{0,90}(?:事实路径|factual\s+path|fallback|兼容路径|compatibility\s+(?:fallback|path)).{0,70}(?:current|当前).{0,30}(?:真源|事实源|source\s+of\s+truth|schema)/i,
      /(?:清理|删除|移除|clean|remove|drop).{0,40}(?:旧事实字段|旧事实路径|legacy\s+factual\s+(?:field|path)s?).{0,40}(?:兼容\s*fallback|compatibility\s+fallback)/i,
      /(?:迁移|migration).{0,30}(?:删除|移除|remove|drop).{0,40}(?:旧事实路径|legacy\s+factual\s+path).{0,40}(?:保留|保持|keep|retain).{0,24}(?:当前入口|current\s+(?:entry|entrypoint))/i,
      /(?:one\s+source\s+of\s+truth).{0,70}(?:legacy\s+alias|dual[-\s]?write).{0,60}(?:remove|drop|converge)|(?:converge|remove|drop).{0,70}(?:one\s+source\s+of\s+truth).{0,70}(?:legacy\s+alias|dual[-\s]?write)/i,
      /(?:迁移|迁完|迁好|migration|migrated).{0,40}(?:只保留|仅保留|只留|keep\s+only).{0,24}(?:一个|one).{0,12}(?:真实入口|real\s+(?:entry|entrypoint))/i,
      /(?:schema|配置|数据).{0,30}(?:迁移|migration).{0,60}(?:只留|只保留|keep\s+only).{0,24}current[\w.-]*.{0,60}(?:删掉|删除|remove|drop).{0,24}legacy[\w.-]*.{0,50}(?:双读|双写|fallback|dual[-\s]?(?:read|write))/i,
      /(?:remove|drop).{0,40}legacy.{0,30}compatibility\s+(?:shim|layer|path).{0,60}(?:converge|unify).{0,30}dual\s+readers?.{0,40}current/i,
    ],
  }),
  signal({
    id: "source_truth_chain",
    polarity: "positive",
    weight: 12,
    reason: "source-of-truth, requirement, design, acceptance, and implementation chain wording",
    routing: true,
    source: "generic",
    patterns: [
      /(?:核对|对照|比对|验证).{0,80}(?:PRD|DESIGN(?:\.md)?|设计稿?|验收标准|验收条件|\bAC\b|acceptance\s+criteria).{0,100}(?:当前代码|源码|current\s+code|source\s+code|运行时(?:状态|日志|表)|状态文件|日志|stderr|数据库|schema|migration|API\s*(?:实际)?返回)/i,
      /(?:PRD|DESIGN(?:\.md)?|设计稿?|验收标准|验收条件|\bAC\b|acceptance\s+criteria).{0,100}(?:当前代码|源码|current\s+code|source\s+code|运行时(?:状态|日志|表)|状态文件|日志|stderr|数据库|schema|migration|API\s*(?:实际)?返回).{0,80}(?:核对|对照|比对|验证)/i,
      /\b(?:verify|cross[-\s]?check|compare|reconcile)\b.{0,80}(?:PRD|DESIGN(?:\.md)?|design\s+(?:spec|source)|acceptance\s+(?:criteria|contract)|\bAC\b).{0,100}(?:current\s+code|source\s+code|runtime\s+(?:state|logs?|table)|state\s+file|logs?|stderr|database|schema|migration|API\s+response)/i,
      /(?:核对|对照|比对|验证).{0,60}(?:[\w./-]+\.(?:ya?ml|json|toml|md)|当前代码|源码|运行时(?:状态|日志|表)|状态文件|日志|stderr|数据库|\bDB\b|schema|migration|API\s*(?:实际)?返回|浏览器(?:实际)?输出|配置文件).{0,100}(?:真源|事实源|source\s+of\s+truth|实际返回|是否一致|一致性)/i,
      /(?:[\w./-]+\.(?:ya?ml|json|toml|md)|当前代码|源码|运行时(?:状态|日志|表)|状态文件|日志|stderr|数据库|\bDB\b|schema|migration|API\s*(?:实际)?返回|浏览器(?:实际)?输出|配置文件).{0,70}(?:核对|对照|比对|验证).{0,100}(?:真源|事实源|source\s+of\s+truth|实际返回|是否一致|一致性)/i,
      /\b(?:verify|cross[-\s]?check|compare|reconcile)\b.{0,70}(?:[\w./-]+\.(?:ya?ml|json|toml|md)|current\s+code|source\s+code|runtime\s+(?:state|logs?|table)|state\s+file|logs?|stderr|database|\bDB\b|schema|migration|API\s+response|browser\s+output|config(?:uration)?\s+file).{0,100}\b(?:against|source\s+of\s+truth|consistent|current\s+truth)\b/i,
      /(?:[\w./-]+\.(?:ya?ml|json|toml|md)|current\s+code|source\s+code|runtime\s+(?:state|logs?|table)|state\s+file|logs?|stderr|database|\bDB\b|schema|migration|API\s+response|browser\s+output|config(?:uration)?\s+file).{0,70}\b(?:verify|cross[-\s]?check|compare|reconcile)\b.{0,100}\b(?:against|source\s+of\s+truth|consistent|current\s+truth)\b/i,
      /(?:先看|查看|检查|确认|核验|拉齐).{0,70}(?:PRD|DESIGN(?:\.md)?|设计稿?|验收标准|验收条件).{0,100}(?:当前实现|当前代码|源码|运行时(?:状态|日志|表)).{0,50}(?:对上|一致|冲突|再动手|方案)/i,
      /(?:PRD|DESIGN(?:\.md)?|设计稿?|验收标准|验收条件).{0,80}(?:当前实现|当前代码|源码|运行时(?:状态|日志|表)).{0,50}(?:对上|一致|冲突).{0,30}(?:再动手|实施|方案)?/i,
      /以.{0,60}(?:当前代码|源码|运行时日志|数据库|API\s*(?:实际)?返回).{0,24}(?:为准|作为真源|作为事实源)/i,
      /(?:以).{0,60}(?:当前代码|源码|运行时日志|数据库|API\s*(?:实际)?返回).{0,20}(?:为准|真源|事实源).{0,60}(?:旧总结|旧文档|旧记录|记忆|别信|不信)/i,
      /(?:需求|requirement|spec).{0,30}(?:设计|design).{0,30}(?:验收|\bAC\b|acceptance).{0,30}(?:实现|implementation|code).{0,30}(?:真源|事实源|source\s+of\s+truth).{0,24}(?:冲突|不一致|conflict)/i,
      /(?:用户原话|用户引用|user(?:'s)?\s+(?:exact\s+)?(?:words|quote)).{0,60}(?:日志|logs?|runtime\s+evidence).{0,30}(?:冲突|不一致|conflict).{0,24}(?:裁决|调和|reconcile|adjudicate)/i,
      /(?:对齐|reconcile|align).{0,30}(?:\bAC\b|acceptance\s+criteria|spec).{0,60}(?:真实实现|real\s+implementation|code).{0,30}(?:证据|evidence)/i,
      /\breconcile\b.{0,40}\bspec\b.{0,40}\bcode\b.{0,40}\bruntime\s+evidence\b/i,
    ],
  }),
  signal({
    id: "failure_triage",
    polarity: "positive",
    weight: 12,
    reason: "debugging requires separating environment failure from business failure",
    routing: true,
    source: "generic",
    patterns: [
      /(?:排障|debug|失败|不生效|报错|异常).{0,60}(?:环境|业务|工具|配置|根因)/i,
      /(?:环境|业务|工具|配置).{0,40}(?:失败|问题|根因|排障)/i,
      /(?:debug|troubleshoot|diagnose|failure|failed|error|exception).{0,60}(?:environment|business|tool|config(?:uration)?|provider|auth|root\s+cause)/i,
      /(?:environment|business|tool|config(?:uration)?|provider|auth).{0,50}(?:failure|failed|error|exception|root\s+cause|debug|troubleshoot|diagnose)/i,
      /(?:MCP|provider|auth|plugin|browser|浏览器插件|工具|权限).{0,60}(?:timeout|401|403|unauthorized|permission\s+denied|连不上|登录失败|找不到|not\s+found|failed|failure|报错|异常).{0,80}(?:诊断|排查|定位|debug|diagnose|troubleshoot)/i,
      /(?:诊断|排查|定位|debug|diagnose|troubleshoot).{0,80}(?:MCP|provider|auth|plugin|browser|浏览器插件|工具|权限).{0,60}(?:timeout|401|403|unauthorized|permission\s+denied|连不上|登录失败|找不到|not\s+found|failed|failure|报错|异常)/i,
      /(?:provider|auth).{0,32}(?:登录失败|认证失败|401|403|unauthorized|login\s+fail(?:ed|ure)?|authentication\s+fail(?:ed|ure)?)/i,
      /(?:plugin|MCP).{0,32}(?:不生效|失效|加载失败|not\s+working|does(?:\s+not|n't)\s+work|failed)/i,
      /(?:browser|浏览器)\s*harness.{0,32}(?:无法连接|连不上|cannot\s+connect|connection\s+failed).{0,50}(?:排查|追查|调查|定位|investigate|diagnose|trace).{0,24}(?:根因|root\s+cause)/i,
    ],
  }),
  signal({
    id: "temporary_mock_boundary",
    polarity: "positive",
    weight: 12,
    reason: "temporary mock, fake data, fallback, or reverse data boundary wording",
    routing: true,
    source: "generic",
    patterns: [
      /(?:mock|fake|placeholder|stub|fallback|反向数据|假数据|内存替代|临时(?:实现|替代|接线)).{0,60}(?:阶段|接线|边界|真实|验收|替代|交付|API|数据|路径)/i,
      /(?:真实路径|真实数据|真实入口|真实\s*API|production|交付|验收).{0,50}(?:mock|fake|placeholder|stub|fallback|反向数据|假数据|内存替代|临时(?:实现|替代|接线))/i,
      /(?:测试用|test[-\s]?only|in[-\s]?memory|内存)(?:.{0,24}(?:store|存储|数据库|repository|对象))?.{0,90}(?:真实持久化|real\s+persistence|production\s+database|\bE2E\b|交付|替换|接入)/i,
      /(?:真实持久化|real\s+persistence|production\s+database|\bE2E\b|交付|替换|接入).{0,90}(?:测试用|test[-\s]?only|in[-\s]?memory|内存)(?:.{0,24}(?:store|存储|数据库|repository|对象))?/i,
      /(?:placeholder|prototype|原型).{0,80}(?:退出|替换|淘汰|移除|exit|replace|remove).{0,80}(?:浏览器|browser|\bE2E\b|交付|真实服务|real\s+(?:service|API|data))/i,
      /(?:fallback|mock|placeholder).{0,40}(?:隐藏|掩盖|hide|mask).{0,50}(?:未完成|未闭环|incomplete|unfinished).{0,30}(?:链路|实现|交付|path|flow|delivery)/i,
    ],
  }),
  signal({
    id: "external_model_review",
    polarity: "positive",
    weight: 12,
    reason: "external or multi-model review with source anchors and decision boundary",
    routing: true,
    source: "generic",
    patterns: [
      /(?:外部模型|多个?模型|dispatch|party[-\s]?review|model\s+review).{0,70}(?:审查|评审|review|真源|source|锚点|裁决|边界)/i,
      /(?:审查|评审|review).{0,50}(?:外部模型|多个?模型|dispatch|source\s+anchor|真源锚点)/i,
      /(?:Claude.{0,30}Grok|Grok.{0,30}Claude|Claude.{0,30}(?:Codex|Gemini)|(?:Codex|Gemini).{0,30}Claude|Codex.{0,30}(?:Grok|Gemini)|(?:Grok|Gemini).{0,30}Codex).{0,50}(?:各自|分别|独立|交叉).{0,24}(?:审查|评审|review)/i,
      /(?:各自|分别|独立|交叉).{0,24}(?:审查|评审|review).{0,50}(?:Claude.{0,30}Grok|Grok.{0,30}Claude|Claude.{0,30}(?:Codex|Gemini)|(?:Codex|Gemini).{0,30}Claude|Codex.{0,30}(?:Grok|Gemini)|(?:Grok|Gemini).{0,30}Codex)/i,
      /\b(?:multiple|several)\s+models?\b.{0,50}\b(?:independent(?:ly)?|separately|cross[-\s]?check)\b.{0,24}\b(?:review|audit)\b/i,
      /(?:让|请|找|再让).{0,16}(?:Claude|Grok|Codex|Gemini).{0,70}(?:独立|再|帮忙)?.{0,24}(?:review|审查|评审|看一下).{0,70}(?:改动|diff|实现|方案|风险|反例|回退)/i,
      /\b(?:ask|have|get)\s+(?:Claude|Grok|Codex|Gemini)\s+to\s+(?:independently\s+)?(?:review|audit)\b.{0,70}(?:change|diff|patch|implementation|plan|risk|regression)/i,
      /(?:多模型|multi[-\s]?model).{0,30}(?:独立|independent).{0,24}(?:会诊|review|audit).{0,40}(?:改动|diff|实现|方案|change|implementation|plan)?/i,
      /\bindependent\b.{0,24}\bmulti[-\s]?model\b.{0,24}\b(?:review|audit)\b/i,
    ],
  }),
  signal({
    id: "model_comparison_only",
    polarity: "negative",
    weight: -34,
    reason: "models are being compared as products rather than reviewing task work",
    routing: false,
    negativeTargets: ["external_model_review"],
    suppressTargets: true,
    source: "generic",
    patterns: [
      /(?:模型|Claude|Grok|Codex|Gemini|provider).{0,80}(?:价格|定价|成本|计费|上下文窗口|token\s*限制|额度|选型比较)/i,
      /(?:价格|定价|成本|计费|上下文窗口|token\s*限制|额度|选型比较).{0,80}(?:模型|Claude|Grok|Codex|Gemini|provider)/i,
      /(?:models?|providers?|Claude|Grok|Codex|Gemini|GPT).{0,80}(?:pricing|prices?|cost|billing|rate\s+limits?|token\s+limits?|context\s+windows?|budget(?:ing)?|procurement|provider\s+selection)/i,
      /(?:pricing|prices?|cost|billing|rate\s+limits?|token\s+limits?|context\s+windows?|budget(?:ing)?|procurement|provider\s+selection).{0,80}(?:models?|providers?|Claude|Grok|Codex|Gemini|GPT)/i,
    ],
  }),
  signal({
    id: "rule_governance",
    polarity: "positive",
    weight: 12,
    reason: "agent rule, AGENTS, CLAUDE, or rule-layer governance wording",
    routing: true,
    source: "generic",
    patterns: [
      /(?:AGENTS\.md|CLAUDE\.md|Claude\s+rules?|agent\s+rules?|入口规则|代理规则).{0,80}(?:清理|去重|分层|归位|下沉|迁移|移动|clean\s*up|deduplicat(?:e|ion)|layer(?:ing)?|relocat(?:e|ion)|move)/i,
      /(?:清理|去重|分层|归位|下沉|迁移|移动|clean\s*up|deduplicat(?:e|ion)|layer(?:ing)?|relocat(?:e|ion)|move).{0,80}(?:AGENTS\.md|CLAUDE\.md|Claude\s+rules?|agent\s+rules?|入口规则|代理规则)/i,
      /(?:AGENTS\.md|CLAUDE\.md).{0,100}(?:流程|能力说明|具体规则).{0,50}(?:下沉|迁移|移动|move|relocate).{0,30}(?:skill|能力层|正确分层|right\s+layer)/i,
      /(?:合并|merge).{0,40}(?:AGENTS\.md|CLAUDE\.md|agent\s+rules?|Claude\s+rules?).{0,40}(?:冲突|重复|conflicting|duplicate).{0,16}(?:规则|rules?)/i,
      /(?:CLAUDE(?:\.md)?\s+rules?|agent\s+rules?|代理规则).{0,50}(?:分开|拆分|分层|separat(?:e|ing)|split|layer).{0,50}(?:常驻事实|always[-\s]?on(?:\s+repository)?\s+facts?).{0,50}(?:能力流程|capability\s+workflows?).{0,40}(?:(?:long\s+)?docs?|文档)/i,
      /(?:agent\s+rules?|代理规则).{0,50}(?:根规则|root\s+rules?).{0,40}(?:skill\s+流程|skill\s+workflows?).{0,30}(?:分层|separate|layer).{0,40}(?:合并|merge).{0,24}(?:旧口径|old\s+wording)/i,
      /(?:agent\s*(?:rules?|规则)|代理规则).{0,50}(?:放|归入|belong(?:s)?).{0,24}(?:根规则|root\s+rules?).{0,24}(?:还是|or).{0,20}skill.{0,40}(?:合并|merge).{0,24}(?:旧口径|old\s+wording)/i,
    ],
  }),
  signal({
    id: "long_running_liveness",
    polarity: "positive",
    weight: 12,
    reason: "long-running agent liveness, progress, inactivity, or stall handling",
    routing: true,
    source: "generic",
    patterns: [
      /(?:coding\s+agent|\bagent\b|worker|provider|bridge|长任务|模型任务).{0,100}(?:activity|heartbeat|progress|stream|流式输出|阶段(?:输出|推进|进展|变化)|工具结果|状态推进).{0,100}(?:timeout|超时|墙钟|kill|杀掉|误杀|续租|inactivity|stalled?|失活|无限续命)/i,
      /(?:timeout|超时|墙钟|kill|杀掉|误杀|续租|inactivity|stalled?|失活|无限续命).{0,100}(?:coding\s+agent|\bagent\b|worker|provider|bridge|长任务|模型任务).{0,100}(?:activity|heartbeat|progress|stream|流式输出|阶段(?:输出|推进|进展|变化)|工具结果|状态推进)/i,
      /heartbeat.{0,80}(?:没有|无|without|no).{0,40}(?:progress|输出|进展|状态推进).{0,50}(?:stalled?|卡住|续命|stall\s+window)/i,
      /heartbeat.{0,80}(?:长时间|长期|很久|半小时|still|alive|running).{0,50}(?:没有|无|without|no).{0,30}(?:progress|输出|进展|状态推进)/i,
      /(?:inactivity\s+window|progress\s+stall\s+window).{0,60}(?:agent|worker|provider|bridge|任务|失活|stalled?)/i,
      /(?:agent|worker|provider|bridge|任务|失活|stalled?).{0,60}(?:inactivity\s+window|progress\s+stall\s+window)/i,
    ],
  }),
  signal({
    id: "control_plane_worker_divergence",
    polarity: "positive",
    weight: 13,
    reason: "control-plane capacity, lease, or queue state diverges from live worker evidence",
    routing: true,
    source: "pack",
    pack: "agent-ops",
    queryTerms: [
      "control-plane-worker-divergence",
      "empty-slot-still-queued",
      "lease-worker-report-mismatch",
    ],
    patterns: [
      /(?:^|[，,。.;；!?！？:：]\s*)(?:(?:kanban|页面|控制面|当前|现在|明明|确实)\s*){0,4}(?:有|还有|仍有|存在)\s*(?:空槽|空闲槽位)[^\n.!?。！？]{0,48}(?:仍|还|一直)[^\n.!?。！？]{0,24}(?:排队|queued|pending)/i,
      /(?:^|[,:;.!?]\s*)(?:(?:in\s+production(?:\s+now)?|currently|right\s+now|live|kanban|control\s+plane|the\s+page)\s*){0,2}(?:(?:there\s+is|we\s+have)\s+(?:an?\s+)?(?:free|available|empty)\s+slot|(?:an?|the)\s+slot\s+(?:is|looks)\s+(?:free|available|empty))[^\n.!?。！？]{0,48}(?:still|yet|remains?)[^\n.!?。！？]{0,24}(?:queued|pending)/i,
      /(?:run|任务)[^\n.!?。！？]{0,24}(?:仍|还|一直|remains?|stays?|is)[^\n.!?。！？]{0,16}(?:排队|queued|pending)[^\n.!?。！？]{0,48}(?:但|可是|although|even\s+though|but)[^\n.!?。！？]{0,24}(?:(?:明明|仍然)?(?:有|还有|仍有|存在)\s*(?:空槽|空闲槽位)|(?:there\s+is\s+)?(?:an?|the)?\s*(?:free|available|empty)\s+slot|(?:an?|the)\s+slot\s+(?:is\s+)?(?:free|available|empty))/i,
      /(?=[^\n.!?。！？]{0,180}(?:capacity|worker\s*pool|执行容量|worker\s*容量))(?=[^\n.!?。！？]{0,180}(?:not\s+full|has\s+room|available\s+capacity|容量未满|还有容量|有余量|capacity\s*(?:is|=)\s*\d+[^\n.!?。！？]{0,40}only\s+\d+\s+workers?\s+(?:are\s+)?active))(?=[^\n.!?。！？]{0,180}(?:queued|pending|排队))[^\n.!?。！？]{1,180}/i,
      /(?=[^\n.!?。！？]{0,180}(?:heartbeats?\s+(?:(?:has|have)\s+)?(?:already\s+)?(?:gone\s+)?(?:expired|timed\s+out|stale)|heartbeat\s+expiry|heartbeat\s+timeout|heartbeat\s*(?:已(?:经)?)?\s*(?:过期|超时|失联)|心跳\s*(?:已(?:经)?)?\s*(?:过期|超时|失联)))(?=[^\n.!?。！？]{0,180}(?:worker|process|进程)[^\n.!?。！？]{0,40}(?:still\s+)?(?:alive|running|keeps?\s+running|还活着|仍在运行))[^\n.!?。！？]{1,180}/i,
      /(?=[^\n.!?。！？]{0,180}(?:dispatch\s+)?(?:lease|租约))(?=[^\n.!?。！？]{0,180}(?:worker\s*report|worker\s*报告))(?=[^\n.!?。！？]{0,180}(?:mismatch|diverg(?:e|es|ed|ence)|out\s+of\s+sync|disagrees?|不一致|没对上|分裂|漂移))[^\n.!?。！？]{1,180}/i,
      /(?=[^\n.!?。！？]{0,180}(?:dispatch))(?=[^\n.!?。！？]{0,180}(?:lease|租约))(?=[^\n.!?。！？]{0,180}(?:worker\s*report|worker\s*报告))(?=[^\n.!?。！？]{0,180}(?:对齐|核对|reconcile|cross[-\s]?check))[^\n.!?。！？]{1,180}/i,
      /(?=[^\n.!?。！？]{0,180}(?:lease|租约)[^\n.!?。！？]{0,48}(?:expired|released|过期|已释放))(?=[^\n.!?。！？]{0,180}(?:worker\s*report|worker\s*报告)[^\n.!?。！？]{0,56}(?:active|running|alive|进程.{0,12}(?:活着|运行)))[^\n.!?。！？]{1,180}/i,
      /(?:^|[\n。.!?！？;；]\s*|\|\|\s*)(?:current\s+live(?:\s+state)?(?:\s+follows)?|current\s+runtime|current\s+state|current|当前(?:实时|运行时|状态)?)(?:\s*(?::|：))?[\s\S]{0,32}(?=[\s\S]{0,240}(?:capacity|worker\s*pool|执行容量|worker\s*容量))(?=[\s\S]{0,240}(?:not\s+full|has\s+room|available\s+capacity|容量未满|还有容量|有余量))(?=[\s\S]{0,240}(?:queued|pending|排队))[\s\S]{1,240}/i,
      /(?:^|[\n。.!?！？;；]\s*|\|\|\s*)(?:current\s+live(?:\s+state)?(?:\s+follows)?|current\s+runtime|current\s+state|current|当前(?:实时|运行时|状态)?)(?:\s*(?::|：))?[\s\S]{0,32}(?=[\s\S]{0,240}(?:lease|租约))(?=[\s\S]{0,240}(?:worker\s*report|worker\s*报告|workerReport))(?=[\s\S]{0,240}(?:(?:mismatch|diverg(?:e|es|ed|ence)|out\s+of\s+sync|disagrees?|不一致|没对上|分裂|漂移)|(?:lease|租约)[\s\S]{0,80}(?:expired|released|过期|已释放)[\s\S]{0,120}(?:worker\s*report|worker\s*报告|workerReport)[\s\S]{0,80}(?:active|running|alive|活着|运行)))[\s\S]{1,240}/i,
      /(?:^|[\n。.!?！？;；]\s*|\|\|\s*)(?:current\s+live(?:\s+state)?(?:\s+follows)?|current\s+runtime|current\s+state|current|当前(?:实时|运行时|状态)?)(?:\s*(?::|：))?[\s\S]{0,32}(?=[\s\S]{0,240}(?:heartbeat|心跳)[\s\S]{0,48}(?:stale|expired|timed\s+out|过期|超时|失联))(?=[\s\S]{0,240}(?:worker|process|进程)[\s\S]{0,48}(?:alive|running|活着|运行))[\s\S]{1,240}/i,
    ],
  }),
  signal({
    id: "control_plane_divergence_ruled_out",
    polarity: "negative",
    weight: -36,
    reason: "control-plane mismatch or liveness divergence was explicitly disproved",
    routing: false,
    negativeTargets: ["control_plane_worker_divergence"],
    suppressTargets: true,
    source: "pack",
    pack: "agent-ops",
    patterns: [
      /(?:lease|dispatch|worker\s*report|heartbeat)[^\n.!?。！？；;]{0,48}(?:mismatch|divergence|expired|out\s+of\s+sync)[^\n.!?。！？；;]{0,48}(?:has\s+been\s+|was\s+|is\s+)?(?:ruled\s+out|disproved|not\s+present|a\s+false\s+alarm)/i,
      /(?:ruled\s+out|disproved|not\s+present|false\s+alarm)[^\n.!?。！？；;]{0,48}(?:lease|dispatch|worker\s*report|heartbeat)[^\n.!?。！？；;]{0,32}(?:mismatch|divergence|expired|out\s+of\s+sync)/i,
      /heartbeat\s+expired\?\s*(?:no|false)[^\n.!?。！？；;]{0,64}heartbeat\s+(?:is\s+)?current/i,
      /(?:no|without)\s+(?:actual\s+)?(?:mismatch|divergence|split)|(?:mismatch|divergence|split)\s+(?:is\s+)?(?:not\s+present|absent|false)/i,
      /(?=[^\n.!?。！？；;]{0,140}(?:lease|租约))(?=[^\n.!?。！？；;]{0,140}(?:worker\s*report|worker\s*报告))(?=[^\n.!?。！？；;]{0,140}(?:\bagree(?:s|d)?\b|\bmatches?\b|in\s+sync|(?<!不)一致|已对齐))[^\n.!?。！？；;]{1,140}/i,
      /(?=[^\n.!?。！？；;]{0,160}(?:heartbeats?\s+(?:(?:has|have)\s+)?(?:expired|timed\s+out|stale)|heartbeat\s+(?:expiry|timeout)|心跳[^\n.!?。！？；;]{0,12}(?:过期|超时|失联)))(?=[^\n.!?。！？；;]{0,160}(?:no\s+(?:live\s+)?worker|worker[^\n.!?。！？；;]{0,24}(?:is\s+)?(?:not\s+alive|dead|stopped|exited)|没有[^\n.!?。！？；;]{0,12}(?:存活|运行)的?\s*worker|worker[^\n.!?。！？；;]{0,12}(?:已退出|已停止|不存活)))[^\n.!?。！？；;]{1,160}/i,
      /(?=[^\n.!?。！？；;]{0,180}(?:queued|pending|排队))(?=[^\n.!?。！？；;]{0,180}(?:expected|normal|as\s+designed|by\s+design|waiting\s+for\s+(?:a\s+)?(?:dependency|approval|scheduledAt|rate\s+limit|backoff)|正常|符合预期|按设计|等待(?:依赖|审批|定时|退避|限流)))[^\n.!?。！？；;]{1,180}/i,
      /(?:runtime|运行时|current\s+state|当前状态)[^\n.!?。！？；;]{0,40}(?:is\s+)?(?:fine|healthy|normal|正常|健康)|(?:no\s+actual\s+incident|没有真实故障|不存在真实故障)/i,
      /\b(?:fixed|resolved|repaired)\b[^\n.!?。！？；;]{0,80}\b(?:mismatch|divergence|out\s+of\s+sync)\b[^\n.!?。！？；;]{0,60}\b(?:yesterday|previously|earlier|last\s+(?:time|run|incident|week))\b|(?:昨天|此前|之前|上次).{0,60}(?:已修复|已解决).{0,60}(?:不一致|分裂|漂移)/i,
      /(?:lease|租约|dispatch|worker\s*report|worker\s*报告|heartbeat|心跳)[^\n.!?。！？；;]{0,48}(?:不一致|分裂|漂移|mismatch|过期)[^\n.!?。！？；;]{0,48}(?:已排除|不存在|已证伪|是误报|状态正常|当前正常)/i,
      /(?:已排除|不存在|已证伪|误报|状态正常|当前正常)[^\n.!?。！？；;]{0,48}(?:lease|租约|dispatch|worker\s*report|worker\s*报告|heartbeat|心跳)[^\n.!?。！？；;]{0,32}(?:不一致|分裂|漂移|mismatch|过期)/i,
    ],
  }),
  signal({
    id: "runtime_reference_context",
    polarity: "negative",
    weight: -34,
    reason: "runtime wording appears only in documentation, fixtures, simulations, UI copy, hypotheticals, or prohibitions",
    routing: false,
    negativeTargets: ["dispatch_runtime_development", "control_plane_worker_divergence"],
    suppressTargets: true,
    source: "generic",
    patterns: [
      /(?:README|docs?|documentation|guide|文档|说明)[^\n]{0,100}(?:example|示例|says?|写着|mentions?|引用|引句|quoted?|phrase|wording|text)/i,
      /(?:example|示例|quoted?|literal\s+text|phrase|wording|引句|字面文本)[^\n]{0,100}(?:README|docs?|documentation|guide|文档|说明)/i,
      /(?:fixture|test\s+fixture|测试夹具|回归样例)[^\n]{0,100}(?:says?|contains?|literal|prompt|example|写着|包含)/i,
      /(?:copy|add|write|insert|复制|加入|写入)[^\n]{0,90}(?:literal\s+text|phrase|quoted\s+sentence|字面文本|原句)[^\n]{0,60}(?:README|docs?|fixture|文档|夹具)/i,
      /\b(?:quote|copy|insert|include|paste)\b[^\n]{0,180}\b(?:proposal|plan|spec|design\s+note|implementation\s+proposal|incident\s+report)\b|\b(?:proposal|plan|spec|design\s+note|implementation\s+proposal|incident\s+report)\b[^\n]{0,140}\b(?:quotes?|quoted|copy|copies|copied|insert|include|contains?)\b|(?:引用|复制|插入|加入).{0,160}(?:提案|方案|规划|规范|设计说明|实施提案|事故报告)|(?:提案|方案|规划|规范|设计说明|实施提案|事故报告).{0,120}(?:引用|复制|插入|加入|包含)/i,
      /(?:provider\s*adapter|(?:model|provider)\s*registry|model\s*resolver|route\s*table|fallback\s*chain)\s+(?:documentation|docs?|example|fixture|proposal|plan)\b/i,
      /\b(?:review|plan|discuss|explain)\s+(?:how\s+to|whether|why)\b(?![\s\S]{0,180}\b(?:then|and\s+then|after\s+that)\b.{0,32}\b(?:implement|fix|change|modify|repair|apply|make)\b.{0,24}\b(?:it|that|this|approved|ai[-\s]?dispatch|provider|registry|resolver|runtime|change|fix)\b)|(?:评审|讨论|规划|解释).{0,24}(?:如何|是否|为什么)(?![\s\S]{0,180}(?:然后|随后|接着|再).{0,24}(?:实现|修复|修改|落地|改造|重构).{0,16}(?:它|这个|该|上述|ai[-\s]?dispatch|provider|registry|resolver|runtime|修复|修改|变更|方案))/i,
      /\b(?:hypothetical|suppose|imagine)\b|\bshould\s+we\b.{0,40}\bsomeday\b|假设.{0,40}(?:会怎样|风险|如果)/i,
      /\b(?:never|must\s+not|should\s+not|do\s+not|don't)\b.{0,100}(?:ai[-\s]?dispatch|provider\s*adapter|model\s*registry|model\s*resolver|route\s*table|fallback\s*chain)|(?:禁止|不得|不要).{0,80}(?:ai[-\s]?dispatch|provider\s*adapter|model\s*registry|model\s*resolver|route\s*table|fallback\s*chain)/i,
      /\b(?:simulate|simulation|mock)\b.{0,120}(?:lease|worker\s*report|heartbeat|ai[-\s]?dispatch)|(?:模拟|仿真).{0,100}(?:租约|worker\s*报告|心跳|ai[-\s]?dispatch)/i,
      /(?:rename|change|update|修改|重命名).{0,80}(?:UI\s+label|warning\s+text|wording|field\s+names?|界面文案|告警文案|字段名)/i,
      /(?:check|assertion|test)[^\n]{0,80}(?:asserts?|expects?)[^\n]{0,80}(?:false|not\s+alive|stopped)|(?:断言|测试).{0,80}(?:为假|不存活|已停止)/i,
      /(?:historical\s+incident\s+note|历史故障记录)[^\n]{0,140}(?:current\s+runtime\s+is\s+healthy|当前运行时健康)/i,
      /(?:update|edit|rewrite|rename|summarize|copy|修改|更新|重写|重命名|整理|复制)[^\n]{0,80}(?:historical\s+(?:incident\s+)?note|incident\s+note|postmortem|retrospective|test\s+(?:case|name)|fixture\s+name|历史(?:故障|事故)?记录|事故复盘|复盘文档|测试用例|测试名称|夹具名称)/i,
      /(?:historical\s+(?:incident\s+)?note|incident\s+note|postmortem|retrospective|test\s+(?:case|name)|历史故障记录|事故复盘|复盘文档|测试用例|测试名称)[^\n]{0,100}(?:says?|mentions?|records?|contains?|describes?|写着|提到|记录|包含|描述)[^\n]{0,100}(?:lease|worker\s*report|heartbeat|queued|pending|mismatch|divergence|out\s+of\s+sync|租约|worker\s*报告|心跳|排队|不一致|分裂|漂移)/i,
      /(?:^|[\n。.!?！？；;]\s*)(?:postmortem|historical\s+(?:incident\s+)?note|incident\s+note|retrospective|test\s+(?:case|name)|reference(?:\s+only)?|事故复盘|复盘(?:记录|文档)?|历史故障记录|事故记录|测试(?:用例|名称)|仅供参考)\s*(?::|：|—|-)\s*[^\n。.!?！？；;]{0,160}(?:ai[-\s]?dispatch|provider\s*adapter|model\s*registry|model\s*resolver|route\s*table|fallback\s*chain|lease|worker\s*report|heartbeat|capacity|slot|queued|pending|mismatch|out\s+of\s+sync|租约|worker\s*报告|心跳|容量|空槽|排队|不一致|分裂|漂移)/i,
      /(?:^|\n)\s*(?:example\s+prompt|sample\s+prompt|expected\s+prompt|fixture(?:\s+input)?|test\s+fixture|ui\s+copy\s+payload|示例提示词|样例提示词|预期提示词|夹具(?:输入)?|测试夹具|界面文案载荷)\s*(?::|：)[\s\S]{0,220}(?:ai[-\s]?dispatch|provider\s*adapter|model\s*registry|model\s*resolver|route\s*table|fallback\s*chain|lease|worker\s*report|workerReport|heartbeat|capacity|slot|queued|pending|租约|worker\s*报告|心跳|容量|空槽|排队)/i,
      /只修改.{0,100}(?:界面文案|告警文案|字段名)/i,
    ],
  }),
  signal({
    id: "dispatch_tool_use_context",
    polarity: "negative",
    weight: -38,
    reason: "ai-dispatch is being invoked as a tool to work on another target, not developed itself",
    routing: false,
    negativeTargets: ["dispatch_runtime_development"],
    suppressTargets: true,
    source: "pack",
    pack: "ai-dispatch",
    patterns: [
      /\b(?:ask|tell|call|run|use)\s+ai[-\s]?dispatch\s*[:：]\s*(?:add|build|implement|develop|modify|change|fix|debug|investigate|diagnose|repair|refactor|migrate|integrate|wire|upgrade)/i,
      /(?:让|叫|用|调用)\s*ai[-\s]?dispatch\s*[:：]\s*(?:新增|实现|开发|修改|修复|调试|排障|重构|迁移|接入|升级)/i,
    ],
  }),
  signal({
    id: "resource_lifecycle_cleanup",
    polarity: "positive",
    weight: 12,
    reason: "owned runtime resources are being discarded, cleaned, released, retained, or recovered",
    routing: true,
    source: "generic",
    patterns: [
      /(?:worktree|branch-env|container|docker|环境资源|运行资源|资源).{0,80}(?:discard|cleanup|clean\s+up|release|reclaim|delete|preserve|retain|丢弃|清理|回收|释放|删除|保留)/i,
      /(?:discard|cleanup|clean\s+up|release|reclaim|delete|preserve|retain|丢弃|清理|回收|释放|删除|保留).{0,80}(?:worktree|branch-env|container|docker|环境资源|运行资源|资源)/i,
    ],
  }),
  signal({
    id: "bridge_runtime_validation",
    polarity: "positive",
    weight: 12,
    reason: "bridge, bot, message service, watchdog, or runtime status validation wording",
    routing: true,
    source: "pack",
    pack: "agent-ops",
    patterns: [
      /(?:\b(?:bot|telegram|wechat|lark|tg|wx)\b|机器人|消息\s*bridge|消息服务|消息通道|飞书|微信).{0,80}(?:验收|验证|状态|一致|日志|重启|运行时|收发|送达|副作用|validate|verify|status|logs?|restart|send|receive|delivery|receipt|polling|watchdog)/i,
      /(?:验收|验证|状态|一致|日志|重启|运行时|收发|送达|副作用|validate|verify|status|logs?|restart|send|receive|delivery|receipt|polling|watchdog).{0,80}(?:\b(?:bot|telegram|wechat|lark|tg|wx)\b|机器人|消息\s*bridge|消息服务|消息通道|飞书|微信)/i,
      /\bbridge\b.{0,56}(?:pid|single[-\s]?instance|status|logs?|restart|send|receive|receipt|polling|watchdog|进程|单实例|状态|日志|重启|收发|回执|轮询)/i,
      /(?:pid|single[-\s]?instance|status|logs?|restart|send|receive|receipt|polling|watchdog|进程|单实例|状态|日志|重启|收发|回执|轮询).{0,56}\bbridge\b/i,
    ],
  }),
  signal({
    id: "bridge_runtime_absent",
    polarity: "negative",
    weight: -36,
    reason: "the task explicitly has no bridge or message send-receive path to validate",
    routing: false,
    negativeTargets: ["bridge_runtime_validation"],
    suppressTargets: true,
    source: "pack",
    pack: "agent-ops",
    patterns: [
      /(?:没有|并无|不存在|不涉及).{0,30}(?:消息通道|消息服务|消息收发|收发路径|bridge|bot)/i,
      /(?:不需要|无需|不用).{0,24}(?:bridge|bot|消息通道|消息服务|消息收发).{0,24}(?:验收|验证|重启|收发)?/i,
      /(?:不要|不必).{0,24}(?:验收|验证|重启).{0,24}(?:bridge|bot|消息通道|消息服务|消息收发)/i,
      /(?:只|仅).{0,24}(?:查看|检查|查询|看).{0,32}(?:bridge|bot).{0,32}(?:pid|状态|进程)/i,
      /(?:只|仅).{0,24}(?:查看|检查|查询|看).{0,32}(?:bridge|bot).{0,32}(?:pid|状态|进程).{0,32}(?:不做|无需|不需要).{0,24}(?:消息)?(?:收发|送达|验收|验证)/i,
      /\b(?:no|without|does\s+not\s+have|doesn't\s+have)\b.{0,40}(?:message\s+(?:channel|service|send(?:ing)?|receiv(?:e|ing)|delivery)|send[-\s]?receive\s+path|bridge|bot)/i,
      /(?:bridge|message\s+(?:channel|service|send(?:ing)?|receiv(?:e|ing))).{0,30}(?:validation\s+is\s+not\s+needed|does\s+not\s+exist|is\s+absent)/i,
      /(?:only\s+)(?:check|inspect|query).{0,32}(?:bridge|bot).{0,32}(?:pid|status|process)/i,
      /(?:only\s+)?(?:check|inspect|query).{0,32}(?:bridge|bot).{0,32}(?:pid|status|process).{0,40}(?:do\s+not|don't|without).{0,24}(?:validate|verify|test).{0,24}(?:message\s+)?(?:send|receive|delivery)/i,
    ],
  }),
  signal({
    id: "design_source_alignment",
    polarity: "positive",
    weight: 12,
    reason: "UI/UX or product design work must align with DESIGN.md or design source",
    routing: true,
    source: "generic",
    patterns: [
      /(?:UI\/UX|产品设计|交互设计|视觉设计|信息架构|DESIGN\.md|design\s+(?:source|spec)).{0,70}(?:对齐|评审|review|align)/i,
      /(?:对齐|评审|review|align).{0,70}(?:UI\/UX|产品设计|交互设计|视觉设计|信息架构|DESIGN\.md|design\s+(?:source|spec))/i,
      /(?:设计稿|高保真稿|原型图?|线框图?|截图|mockup|wireframe|screenshot|design\s+comp).{0,70}(?:对照|比对|核对|还原|检查.{0,16}一致|compare|align|match|reproduce|check.{0,16}consisten)/i,
      /(?:对照|比对|核对|还原|compare|align|match|reproduce|check).{0,70}(?:设计稿|高保真稿|原型图?|线框图?|截图|mockup|wireframe|screenshot|design\s+comp)/i,
      /(?:设计稿|高保真稿|原型图?|线框图?|截图|mockup|wireframe|screenshot|design\s+comp).{0,70}(?:评审|评价|判断|review|evaluate|assess)/i,
      /(?:评审|评价|判断|review|evaluate|assess).{0,70}(?:设计稿|高保真稿|原型图?|线框图?|截图|mockup|wireframe|screenshot|design\s+comp)/i,
      /(?:Linear|Apple|风格参考|style\s+reference|design\s+reference).{0,70}(?:页面|界面|UI|UX|设计稿|mockup|screenshot).{0,40}(?:对齐|评审|review|align)/i,
      /(?:对齐|评审|review|align).{0,70}(?:页面|界面|UI|UX|设计稿|mockup|screenshot).{0,40}(?:Linear|Apple|风格参考|style\s+reference|design\s+reference)/i,
      /(?:按|对照|根据).{0,16}(?:设计稿|mockup|design\s+comp).{0,40}(?:实现|开发|还原|implement|build).{0,24}(?:页面|UI|界面|page)/i,
      /(?:Linear|Apple).{0,16}(?:风格|style).{0,32}(?:设计|实现|build|design).{0,24}(?:页面|UI|界面|page)/i,
      /(?:现有截图|existing\s+screenshot).{0,50}(?:项目\s*)?(?:design\s+system|设计系统).{0,50}(?:为准|作为.{0,12}(?:设计源|source)|as\s+(?:the\s+)?sources?).{0,50}(?:改|调整|change|update|modify).{0,24}(?:UX|UI|页面|界面)/i,
      /(?:use|以).{0,24}(?:现有截图|existing\s+screenshot).{0,50}(?:项目\s*)?(?:design\s+system|设计系统).{0,50}(?:为准|as\s+(?:the\s+)?sources?).{0,50}(?:before|再).{0,24}(?:改|调整|changing|change|update).{0,20}(?:UX|UI|页面|界面)/i,
      /(?:列表页|页面|UX|UI).{0,40}(?:体验)?(?:怎么改|如何改|change|improve).{0,50}(?:先看|先对照|first\s+(?:review|inspect)).{0,40}(?:现有截图|existing\s+screenshot).{0,40}(?:项目)?(?:设计系统|design\s+system)/i,
    ],
  }),
  signal({
    id: "information_design",
    polarity: "positive",
    weight: 12,
    reason: "attention hierarchy, concept slimming, or low mental-load information design wording",
    routing: true,
    source: "generic",
    patterns: [
      /(?:用户可见|面向用户|页面|界面|控制台|仪表盘|报表|文档|CLI).{0,60}(?:信息层级|视觉层级|注意力层级|注意力分层|认知负担|心智负担|低心智|概念瘦身|信息分层)/i,
      /(?:信息层级|视觉层级|注意力层级|注意力分层|认知负担|心智负担|低心智|概念瘦身|信息分层).{0,60}(?:用户可见|面向用户|页面|界面|控制台|仪表盘|报表|文档|CLI|体验)/i,
      /(?:user[-\s]?visible|user[-\s]?facing|\bUI\b|page|screen|console|dashboard|report|documentation|\bCLI\b).{0,70}(?:(?:information|content|visual|attention)\s+hierarch(?:y|ies)|cognitive\s+load|mental\s+load|progressive\s+disclosure)/i,
      /(?:(?:information|content|visual|attention)\s+hierarch(?:y|ies)|cognitive\s+load|mental\s+load|progressive\s+disclosure).{0,70}(?:user[-\s]?visible|user[-\s]?facing|\bUI\b|page|screen|console|dashboard|report|documentation|\bCLI\b)/i,
      /(?:用户可见|面向用户|页面|界面|控制台|仪表盘|报表|文档|CLI).{0,80}(?:字段|概念|卡片|入口).{0,100}(?:状态.{0,30}(?:影响|风险).{0,30}下一步|第一层|下沉|只保留|打平|分层|瘦身)/i,
      /(?:user[-\s]?visible|user[-\s]?facing|\bUI\b|page|screen|console|dashboard|report|documentation|\bCLI\b).{0,80}(?:fields?|concepts?|cards?|entries).{0,100}(?:status.{0,30}(?:impact|risk).{0,30}next\s+step|first\s+layer|move\s+down|keep\s+only|flatten|layer|simplif)/i,
      /(?:页面|界面|用户页|控制台|dashboard).{0,40}(?:卡片|模块).{0,24}(?:嵌套太多|层级太深|过度嵌套|too\s+(?:deeply\s+)?nested)/i,
      /(?:用户页|用户页面|user[-\s]?facing\s+(?:page|screen)).{0,50}(?:只保留|keep\s+only).{0,50}(?:状态|status).{0,24}(?:风险|risk).{0,24}(?:下一步|next\s+step)/i,
      /(?:用户可见|user[-\s]?visible|user[-\s]?facing).{0,40}(?:信息架构|information\s+architecture).{0,24}(?:太重|太复杂|过重|heavy|complex)/i,
      /(?:控制台|控制面板|console|control\s+panel).{0,40}(?:概念太多|概念过多|too\s+many\s+concepts?).{0,80}(?:用户(?:第一眼|先)|first\s+view|show).{0,40}(?:状态|status).{0,20}(?:影响|impact).{0,20}(?:操作|动作|actions?).{0,70}(?:内部字段|internal\s+fields?).{0,30}(?:详情|details?)/i,
      /(?:控制台|控制面板|console|control\s+panel).{0,60}(?:状态|status).{0,20}(?:影响|impact).{0,20}(?:操作|动作|actions?).{0,70}(?:内部字段|internal\s+fields?).{0,30}(?:下沉|放入|move|put).{0,20}(?:详情|details?)/i,
    ],
  }),
  signal({
    id: "comprehension_failure",
    polarity: "positive",
    weight: 12,
    reason: "the user directly says they did not understand and needs a different explanation",
    routing: true,
    source: "generic",
    patterns: [
      /(?:^|[。！？!?]\s*)(?:我|这个我)?(?:还是|仍然|依然)?(?:没听懂|不明白|看不懂|理解不了|没跟上)(?:.{0,60}(?:简单|换个方式|具体例子|举例|再讲|解释))?/i,
      /(?:^|[.!?]\s*)(?:I\s+)?(?:still\s+)?(?:do\s+not|don't|did\s+not|didn't|cannot|can't)\s+(?:understand|follow)|(?:^|[.!?]\s*)(?:this|that|it)\s+(?:still\s+)?does(?:\s+not|n't)\s+make\s+sense\s+to\s+me/i,
      /^(?:我)?(?:还是|仍然|依然)?(?:没看明白|没看懂|没理解)(?:.{0,40}(?:换个说法|换种说法|再说一遍|解释|五岁小孩|讲简单点))?/i,
      /^(?:太)?(?:啰嗦|绕).{0,20}(?:讲人话|说简单点|简短点)/i,
      /^(?:请)?再通俗一点(?:讲|解释|说)?/i,
      /^I\s+am\s+lost.{0,40}(?:explain|teach|say).{0,24}(?:like\s+I(?:'m|\s+am)\s+five|ELI5)/i,
    ],
  }),
  signal({
    id: "overengineering_review",
    polarity: "positive",
    weight: 12,
    reason: "a concrete change or plan is being reviewed for unjustified complexity or scope",
    routing: true,
    source: "generic",
    patterns: [
      /(?:review|审查|评审|看看|检查|有没有|是不是).{0,70}(?:diff|patch|改动|方案|实现|小\s*bug|change|plan|implementation|requirement).{0,90}(?:过度设计|过度抽象|无依据抽象|无依据\s*fallback|范围膨胀|scope\s+creep|over[-\s]?engineer(?:ed|ing)?|too\s+complex)/i,
      /(?:diff|patch|改动|方案|实现|小\s*bug).{0,90}(?:过度设计|无依据抽象|范围膨胀|scope\s+creep|over[-\s]?engineer(?:ed|ing)?|too\s+complex)/i,
      /(?:over[-\s]?engineer(?:ed|ing)?|too\s+complex|scope\s+creep).{0,70}(?:diff|patch|change|plan|implementation|requirement)/i,
      /(?:implementation|plan|diff|patch).{0,40}(?:under\s+review|being\s+reviewed).{0,40}(?:over[-\s]?engineer(?:ed|ing)?|too\s+complex|scope\s+creep)/i,
      /(?:小修复|小改动|tiny\s+fix|small\s+fix).{0,80}(?:没有消费者|无消费者|没有消费方|no\s+consumer|speculative).{0,40}(?:预留抽象|抽象层?|abstractions?|layers?).{0,60}(?:review|评审|过度设计|over[-\s]?engineer)?/i,
      /(?:小修复|小改动|tiny\s+fix|small\s+fix).{0,60}(?:预留抽象|抽象层?|speculative\s+abstractions?|speculative\s+layers?).{0,50}(?:没有消费者|无消费者|没有消费方|no\s+consumer)/i,
    ],
  }),
  signal({
    id: "architecture_quality",
    polarity: "positive",
    weight: 13,
    reason: "cohesive architecture, clean logic, or root-cause implementation wording",
    routing: true,
    source: "generic",
    queryTerms: [
      "干净改法",
      "干净重构",
      "链路清理",
      "清理链路",
      "implementation-chain-cleanup",
      "engineering-quality",
      "root-cause-fix",
      "clean-refactor",
    ],
    patterns: [
      /(?:干净改法|干净重构|最干净有效的改法|链路清理|清理链路|最终态重构).{0,80}(?:现有实现|代码变更|实现|链路|重构|清理|优化|改法)/i,
      /(?:现有实现|代码变更|实现|链路|重构|清理|优化|改法).{0,80}(?:干净改法|干净重构|最干净有效的改法|链路清理|清理链路|最终态重构)/i,
      /(?:现有|当前)(?:实现|代码|调用|运行时|数据)?.{0,20}(?:链路|调用链|路径|流程).{0,70}(?:梳理|追踪|清理|重构|最终态|无残留)/i,
      /(?:梳理|追踪|清理|重构|最终态|无残留).{0,70}(?:现有|当前)(?:实现|代码|调用|运行时|数据)?.{0,20}(?:链路|调用链|路径|流程)/i,
      /\b(?:map|trace|clean(?:up)?|refactor)\b.{0,70}\b(?:current|existing)\s+(?:implementation|code|call|runtime|data)?\s*(?:chain|path|flow|pipeline)\b|\b(?:current|existing)\s+(?:implementation|code|call|runtime|data)?\s*(?:chain|path|flow|pipeline)\b.{0,70}\b(?:map|trace|clean(?:up)?|refactor)\b/i,
      /(?:干净|无残留|最终态|clean\s+final[-\s]?state|clean\s+end[-\s]?state).{0,40}(?:重构|实现|架构|refactor|implementation|architecture)/i,
      /(?:重构|refactor).{0,80}(?:不要|不再|移除|删除|without|remove).{0,40}(?:临时兼容层|兼容层|旧分支|fallback|compatibility\s+(?:layer|clutter)|stale\s+branches|残留)/i,
      /(?:refactor|cleanup|split).{0,80}(?:cohesive\s+(?:module|architecture)|module\s+boundar(?:y|ies)|dependency\s+seam|module\s+responsibilit(?:y|ies)|fallback\s+removal)/i,
      /(?:cohesive\s+(?:module|architecture)|module\s+boundar(?:y|ies)|dependency\s+seam|module\s+responsibilit(?:y|ies)|fallback\s+removal|module\s+boundary\s+cleanup).{0,80}(?:refactor|cleanup|split|remove|optimi[sz]e)/i,
      /(?:模块边界|职责拆分|职责分离|fallback\s+removal|module\s+boundary\s+cleanup).{0,70}(?:重构|清理|拆分|移除|删除|优化)/i,
      /(?:重构|清理|拆分|移除|删除|优化).{0,70}(?:模块边界|职责拆分|职责分离|fallback\s+removal|module\s+boundary\s+cleanup)/i,
      /(?:重构|refactor).{0,60}(?:模块|module).{0,80}(?:根因|root[-\s]?cause).{0,50}(?:高内聚|低耦合|cohesive|coupling)/i,
      /(?:重构|refactor).{0,60}(?:模块|module).{0,80}(?:高内聚|低耦合|cohesive|coupling).{0,50}(?:根因|root[-\s]?cause)/i,
      /(?:\bOME\b|oh[-\s]?my[-\s]?experience|召回引擎|检索引擎|retrieval).{0,100}(?:高内聚|低耦合|逻辑干净|无历史包袱|不要历史包袱|cohesive\s+architecture|root[-\s]?cause\s+fix).{0,50}(?:重构|优化|refactor|improve|clean|cleanup)?/i,
      /(?:链路).{0,16}(?:干净|清洗|清理|残留|无残留)|(?:干净|清洗|清理|残留|无残留).{0,16}(?:链路)/i,
      /(?:重构|refactor).{0,50}(?:不留|移除|删除|without|remove).{0,40}(?:旧兼容链路|legacy\s+compatibility\s+(?:chain|path)|stale\s+compatibility\s+(?:chain|path))/i,
      /\bclean\b.{0,30}\bexisting[-\s]?chain\b.{0,30}\bfinal[-\s]?state\b.{0,20}\brefactor\b/i,
    ],
  }),
  signal({
    id: "retrieval_engine_architecture",
    polarity: "positive",
    weight: 13,
    reason: "OME retrieval-engine signal, routing, matching, or scoring architecture work",
    routing: true,
    source: "generic",
    patterns: [
      /(?:\bOME\b|oh[-\s]?my[-\s]?experience).{0,100}(?:召回引擎|检索引擎|retrieval\s+engine|signal\s+registry|召回评分|retrieval\s+scoring|card\s+matching|经验卡召回)/i,
      /(?:\bOME\s+match\b|\bOME\b|oh[-\s]?my[-\s]?experience).{0,80}(?:漏召回|误召回|串卡|召回失败|no\s+match|missed\s+recall|false\s+(?:positive|negative)).{0,100}(?:signal|scoring|score|filter|render|scope|ranking|matcher)/i,
      /(?:漏召回|误召回|串卡|召回失败|no\s+match|missed\s+recall|false\s+(?:positive|negative)).{0,80}(?:signal|scoring|score|filter|render|scope|ranking|matcher).{0,100}(?:\bOME\b|oh[-\s]?my[-\s]?experience)/i,
      /(?:经验卡|experience\s+cards?).{0,80}(?:漏召回|误召回|串卡|召回失败|no\s+match|missed\s+recall|false\s+(?:positive|negative)).{0,100}(?:recall\s+eval|signal|scoring|score|filter|render|scope|ranking|matcher)/i,
      /(?:recall\s+eval|signal|scoring|score|filter|render|scope|ranking|matcher).{0,100}(?:经验卡|experience\s+cards?).{0,80}(?:漏召回|误召回|串卡|召回失败|no\s+match|missed\s+recall|false\s+(?:positive|negative))/i,
      /(?:\bOME\b|oh[-\s]?my[-\s]?experience).{0,90}(?:signal.{0,24}(?:score|scoring).{0,24}filter.{0,24}render|recall\s+eval.{0,50}(?:matcher|scorer))/i,
      /(?:召回引擎|检索引擎|retrieval\s+engine).{0,80}(?:架构|信号(?:注册|识别)|匹配|评分|排序|路由|precision|recall|scoring|routing|matching)/i,
      /(?:架构|信号(?:注册|识别)|匹配|评分|排序|路由|precision|scoring|routing|matching).{0,80}(?:召回引擎|检索引擎|retrieval\s+engine)/i,
      /\bOME\s+match\b.{0,40}(?:漏召回|误召回|串卡|召回失败|no\s+match|missed\s+recall)/i,
      /\bOME\b.{0,40}(?:signal[-\s]?score\s+eval|retrieval\s+recall\s+eval)/i,
      /\bOME\b.{0,32}(?:经验卡|experience\s+cards?).{0,32}(?:误召回|漏召回|串卡|false\s+(?:positive|negative)|missed\s+recall)/i,
      /\bOME\b.{0,32}recall\s+eval.{0,32}non[-\s]?inferior(?:ity)?/i,
    ],
  }),
  signal({
    id: "high_risk_action",
    polarity: "positive",
    weight: 14,
    reason: "high-risk irreversible action requires explicit authorization",
    routing: true,
    source: "generic",
    patterns: [
      /(?:git\s+push|push|开\s*PR|pull\s+request|发布|部署|生产|删除|授权|付费|额度|高风险|不可逆|production).{0,70}(?:确认|授权|先问|审批|执行|操作)/i,
      /(?:确认|授权|先问|审批).{0,50}(?:push|PR|发布|部署|生产|删除|付费|高风险|不可逆)/i,
      /\b(?:ask|wait|require|need|get)\b.{0,30}\b(?:approval|authorization|permission|confirmation)\b.{0,60}\b(?:before|to)\b.{0,24}\b(?:push|deploy|release|publish|delete|remove|open\s+(?:a\s+)?PR|change\s+production|spend)\b/i,
      /\b(?:push|deploy|release|publish|delete|remove|open\s+(?:a\s+)?PR|change\s+production|spend)\b.{0,60}\b(?:after|before|until|requires?)\b.{0,24}\b(?:approval|authorization|permission|confirmation)\b/i,
      /\b(?:authorize|approve|grant\s+permission)\b.{0,40}\b(?:push|deploy|release|publish|delete|remove|open\s+(?:a\s+)?PR|change\s+production|spend)\b/i,
      /\bgit\s+push\b/i,
      /(?:部署|发布|release|deploy|publish).{0,50}(?:生产|production|版本|release|包|package|服务|service|应用|app)/i,
      /(?:生产|production).{0,50}(?:部署|发布|release|deploy|publish)/i,
      /(?:删除|清空|drop|truncate).{0,50}(?:生产数据|生产数据库|数据库里的?记录|数据库记录|用户数据|production\s+(?:data|database)|database\s+(?:records?|data)|user\s+data)/i,
      /(?:修改|更新|change|update).{0,40}(?:生产配置|production\s+config(?:uration)?)/i,
      /(?:购买|付费|充值|spend|purchase|buy).{0,40}(?:额度|credits?|美元|money|budget)/i,
      /(?:修改|变更|change|update).{0,30}(?:生产配置|production\s+config(?:uration)?).{0,50}(?:确认|批准|授权|approval|authorization)|(?:生产配置|production\s+config(?:uration)?).{0,50}(?:确认|批准|授权|approval|authorization).{0,30}(?:修改|变更|change|update)/i,
      /\bbefore\s+chang(?:e|ing)\s+production\s+config(?:uration)?\b.{0,50}\bask\b.{0,30}\b(?:explicit\s+)?approval\b/i,
      /(?:未(?:经|获)|没有|缺少).{0,12}(?:授权|批准|确认).{0,24}(?:不要|不得|禁止).{0,24}(?:(?:删除|清空).{0,24}(?:线上|生产).{0,12}(?:数据|记录)|(?:修改|变更).{0,20}生产配置)/i,
      /(?:先)?不要.{0,12}(?:删|删除|清空).{0,24}(?:这批)?线上数据.{0,40}(?:拿到|获得).{0,12}(?:授权|批准).{0,20}(?:再动手|再执行)/i,
      /\b(?:do\s+not|don't|must\s+not)\b.{0,24}(?:delete|remove).{0,24}(?:online|production).{0,12}(?:data|records?).{0,40}(?:until|without).{0,20}(?:authorized|approval|authorization|permission)/i,
    ],
  }),
  signal({
    id: "high_risk_authorized",
    polarity: "negative",
    weight: -38,
    reason: "the user has explicitly authorized the exact irreversible action",
    routing: false,
    negativeTargets: ["high_risk_action"],
    suppressTargets: true,
    source: "generic",
    patterns: [
      /(?:我|用户).{0,8}(?:已|已经|现已|明确).{0,8}(?:授权|批准|同意)(?:你)?.{0,28}(?:git\s+push|push|开\s*PR|发布|部署|删除|生产操作|付费|购买额度)/i,
      /我.{0,6}(?:同意|批准|授权)你.{0,24}(?:git\s+push|push|开\s*PR|发布|部署|删除|生产操作|付费|购买额度)/i,
      /\bI\s+(?:explicitly\s+|now\s+)?(?:authorize|approve|grant\s+(?:you\s+)?permission)\s+(?:you\s+)?to\s+(?:push|deploy|release|publish|delete|remove|open\s+(?:a\s+)?PR|change\s+production|spend)\b/i,
      /\b(?:the\s+)?user\s+has\s+(?:explicitly\s+)?(?:authorized|approved)\s+(?:you\s+)?to\s+(?:push|deploy|release|publish|delete|remove|open\s+(?:a\s+)?PR|change\s+production|spend)\b/i,
      /\byou\s+(?:are|have\s+been)\s+(?:explicitly\s+)?authorized\s+to\s+(?:push|deploy|release|publish|delete|remove|open\s+(?:a\s+)?PR|change\s+production|spend)\b/i,
    ],
  }),
  signal({
    id: "git_operation",
    polarity: "positive",
    weight: 14,
    reason: "explicit Git, diff, stage, commit, or worktree operation",
    routing: false,
    source: "generic",
    patterns: [
      /\bgit\s+(?:status|diff|add|commit|push|checkout|switch|branch|restore|reset|worktree|merge|rebase|stash|show|log)\b/i,
      /\b(?:commit|push|staged|unstaged|dirty\s+worktree|worktree|diff)\b/i,
      /\b(?:stage|unstage)\b.{0,24}\b(?:files?|changes?|diff|patch)\b|\b(?:files?|changes?|diff|patch)\b.{0,24}\b(?:stage|unstage)\b/i,
      /脏工作区|暂存|提交前|提交|推送|回滚|未提交|无关改动|本任务\s*diff|只处理.{0,20}diff|工作区.{0,20}diff|开\s*PR/i,
    ],
  }),
  signal({
    id: "git_source_noise",
    polarity: "negative",
    weight: -34,
    reason: "Git, GitHub, commit, or diff wording is only a source/background mention, not a local worktree operation",
    routing: false,
    negativeTargets: ["git_operation", "worktree_diff_operation"],
    suppressTargets: true,
    source: "generic",
    patterns: [
      /(?:GitHub|github|PR|issue|commit|diff|git).{0,50}(?:只是|仅仅|只作为|资料来源|背景|source|reference)/i,
      /(?:只是|仅仅|只作为|资料来源|背景|source|reference).{0,50}(?:GitHub|github|PR|issue|commit|diff|git)/i,
      /(?:读|阅读|查看|研究).{0,30}(?:GitHub|github|PR|issue|commit).{0,40}(?:背景|资料|讨论|历史)/i,
    ],
  }),
  signal({
    id: "worktree_read_only",
    polarity: "negative",
    weight: -36,
    reason: "Git diff or worktree inspection is explicitly read-only",
    routing: false,
    negativeTargets: ["worktree_diff_operation"],
    suppressTargets: true,
    source: "generic",
    patterns: [
      /(?:只读|只查看|仅查看).{0,40}(?:git\s*)?(?:diff|status|工作区).{0,60}(?:不修改|不改动|不操作|不暂存|不提交)/i,
      /(?:不修改|不改动|不操作)[、和以及或/,\s]{1,8}(?:暂存|提交|推送)|(?:不暂存)[、和以及或/,\s]{1,8}(?:不?提交|不?推送)/i,
      /\bread[-\s]?only\b.{0,50}\b(?:git\s+)?(?:diff|status|worktree)\b.{0,60}\b(?:do\s+not|don't|without)\s+(?:modify|edit|stage|commit|push)/i,
      /\b(?:do\s+not|don't)\s+(?:modify|edit)(?:\s*,?\s*(?:stage|commit|push|or|and)){1,6}\b/i,
    ],
  }),
  signal({
    id: "worktree_diff_operation",
    polarity: "positive",
    weight: 14,
    reason: "dirty worktree, diff, stage, or commit-scope operation",
    routing: true,
    source: "generic",
    patterns: [
      /\bgit\s+(?:add|commit|push|checkout|switch|restore|reset|merge|rebase|stash)\b/i,
      /\b(?:dirty\s+worktree|staged|unstaged|unrelated\s+dirty|commit\s+scope)\b/i,
      /\b(?:before|prepare(?:d|ing)?\s+to|ready\s+to)\s+(?:stage|commit|push|restore|reset|checkout|switch|merge|rebase|stash)\b/i,
      /\b(?:stage|commit|push|restore|reset|checkout|switch|merge|rebase|stash)\b.{0,24}\b(?:changes?|files?|diff|worktree|branch)\b/i,
      /\bgit\s+stage\b.{0,40}(?:用户改动|本任务|范围|diff|changes?|files?)/i,
      /\b(?:modify|edit|format|clean|isolate)\b.{0,40}\b(?:diff|worktree|changes?)\b|\b(?:diff|worktree|changes?)\b.{0,40}\b(?:modify|edit|format|clean|isolate)\b/i,
      /脏工作区|暂存|未提交|无关改动|提交范围|提交前|推送前|切换分支|变基|贮藏/i,
      /(?:git|分支|工作区|worktree|diff|提交).{0,36}(?:合并|回滚)|(?:合并|回滚).{0,36}(?:git|分支|工作区|worktree|diff|提交)/i,
      /(?<![不未勿])(?:修改|整理|格式化|清理|隔离).{0,32}(?:diff|工作区|改动)|(?:diff|工作区|改动).{0,32}(?<![不未勿])(?:修改|整理|格式化|清理|隔离)/i,
      /(?:继续)?(?:改|修改|编辑).{0,20}(?:代码|实现|code).{0,100}\bgit\s+status\b.{0,80}(?:用户(?:已有)?脏改|用户已有改动|dirty\s+user\s+changes).{0,60}(?:本任务|当前任务|current[-\s]?task).{0,24}diff.{0,24}(?:分开|隔离|isolate|separate)/i,
    ],
  }),
  signal({
    id: "historical_session_lookup",
    polarity: "positive",
    weight: 12,
    reason: "explicit historical session, Spool UUID, or cross-session evidence lookup",
    routing: true,
    source: "pack",
    pack: "spool",
    patterns: [
      /\bspool\b.{0,40}(?:查|搜|看|找|翻|找回|回溯|读取|恢复|定位|search|find|look\s*up|inspect|trace|recover|read).{0,70}(?:上次|之前|那轮|历史|旧|会话|线程|怎么修|怎么处理|修复|处理|证据|session|thread|previous|last|historical|fix(?:ed)?|evidence|uuid|sourceRefs|messageId|turn\s*id|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/i,
      /(?:查|搜|看|找|翻|找回|回溯|读取|恢复|定位|search|find|look\s*up|inspect|trace|recover|read).{0,40}\bspool\b.{0,70}(?:上次|之前|那轮|历史|旧|会话|线程|怎么修|怎么处理|修复|处理|证据|session|thread|previous|last|historical|fix(?:ed)?|evidence|uuid|sourceRefs|messageId|turn\s*id|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/i,
      /\bspool\b.{0,30}\bshow\b.{0,50}(?:uuid|sourceRefs|messageId|turn\s*id|[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})/i,
      /(?:查|搜索|找回|回溯|恢复|交接|lookup|search|trace|recover|handoff).{0,50}(?:历史会话|旧线程|跨会话|session\s*UUID|Spool\s*UUID|sourceRefs|messageId|turn\s*id)/i,
      /(?:历史会话|旧线程|跨会话|session\s*UUID|Spool\s*UUID|sourceRefs|messageId|turn\s*id).{0,50}(?:查|搜索|找回|回溯|恢复|交接|lookup|search|trace|recover|handoff)/i,
    ],
  }),
  signal({
    id: "business_goal_discussion",
    polarity: "negative",
    weight: -36,
    reason: "business or OKR goal discussion, not agent goal execution",
    routing: false,
    negativeTargets: ["goal_execute"],
    suppressTargets: true,
    source: "pack",
    pack: "agent-goal",
    patterns: [/公司.{0,12}目标|业务.{0,12}目标|OKR|指标|增长目标|用户规模目标|拿下\d+.*用户|今年.{0,8}目标/],
  }),
  signal({
    id: "explain_only",
    polarity: "negative",
    weight: -24,
    reason: "explanation or discussion only",
    routing: false,
    negativeTargets: ["explicit_execute", "goal_execute", "dispatch_runtime_development", "control_plane_worker_divergence"],
    suppressTargets: true,
    source: "generic",
    patterns: [
      /(?:只|仅|只是|仅仅).{0,24}(?:了解|讨论|解释|说明|分析)(?:原因|原理|背景)?/i,
      /(?:不要|不用|不需|无需|无须|不必|先别|暂不).{0,24}(?:执行|实现|修改|修复|运行|落地|改代码|动代码)|不(?:执行|实现|修改|修复|运行|落地|改代码|动代码)/i,
      /\b(?:explain|discuss|analy[sz]e)\s+only\b/i,
      /\bwithout\s+(?:(?:execute|executing?|implement|implementing?|run|running?)\b|(?:modify|modifying?|fix|fixing?|change|changing?|edit|editing?)(?:\s+or\s+(?:modify|modifying?|fix|fixing?|change|changing?|edit|editing?))?\s+(?:any\s+)?(?:code|runtime|implementation|anything)\b)/i,
      /\b(?:do\s+not|don't|no\s+need\s+to)\s+(?:(?:execute|implement|run)\b|(?:modify|fix|change|edit)\s+(?:any\s+)?(?:code|runtime|implementation|anything|it)\b)/i,
      /\b(?:no|without)\s+(?:runtime|code|implementation)\s+changes?\b|\bno\s+(?:runtime|code|implementation)\s+change\s+(?:is\s+)?requested\b/i,
      /\b(?:quote|document|describe)\b.{0,80}\b(?:phrase|example|guide|documentation)\b/i,
      /\b(?:reviewed|discussed|documented)\s+(?:how\s+to|whether)\b/i,
      /\bexplain\s+(?:what|why|how)\b.{0,80}\b(?:means?|concept|term)\b/i,
    ],
  }),
]);

const SIGNAL_BY_ID = new Map<string, Readonly<SignalDefinition>>();
for (const definition of SIGNAL_REGISTRY) {
  if (SIGNAL_BY_ID.has(definition.id)) throw new Error(`duplicate signal definition: ${definition.id}`);
  SIGNAL_BY_ID.set(definition.id, definition);
}

export function listSignalDefinitions(options: { source?: SignalSource; pack?: string } = {}): Readonly<SignalDefinition>[] {
  return SIGNAL_REGISTRY.filter((definition) =>
    (!options.source || definition.source === options.source)
    && (!options.pack || definition.pack === options.pack)
  );
}

export function getSignalDefinition(id: unknown): Readonly<SignalDefinition> | null {
  return SIGNAL_BY_ID.get(String(id || "").trim()) || null;
}

export function isKnownSignalId(id: unknown): boolean {
  return Boolean(getSignalDefinition(id));
}

export function getRoutingSignalIds(): string[] {
  return SIGNAL_REGISTRY.filter((definition) => definition.routing).map((definition) => definition.id);
}

export function getSignalNegativeTargets(id: unknown): string[] {
  return [...(getSignalDefinition(id)?.negativeTargets || [])];
}

export function getSignalQueryTerms(id: unknown): string[] {
  return [...(getSignalDefinition(id)?.queryTerms || [])];
}

export function validateSignalIds(values: unknown): SignalValidationResult {
  const ids = uniqueStrings(Array.isArray(values) ? values : values == null ? [] : [values]);
  const known = ids.filter((id) => SIGNAL_BY_ID.has(id));
  const unknown = ids.filter((id) => !SIGNAL_BY_ID.has(id));
  return { ok: unknown.length === 0, known, unknown };
}

export function matchesSignalDefinition(definition: SignalDefinition, text: unknown): boolean {
  const value = String(text || "");
  const composed = Boolean(matchSemanticSignalComposition(definition.id, value));
  if (semanticSignalReplacesDirectPatterns(definition.id)) return composed;
  const direct = definition.patterns.some((pattern) => {
    pattern.lastIndex = 0;
    return pattern.test(value);
  });
  return direct || composed;
}

export function matchSignalDefinitions(text: unknown): Readonly<SignalDefinition>[] {
  return SIGNAL_REGISTRY.filter((definition) => matchesSignalDefinition(definition, text));
}

function uniqueStrings(values: unknown[]): string[] {
  return Array.from(new Set(values.map((value) => String(value || "").trim()).filter(Boolean)));
}
